import {
  Users, Clock, CalendarDays, KanbanSquare, LifeBuoy, Wallet,
  Receipt, Laptop, BarChart3, Target, UserPlus, MessagesSquare,
  GraduationCap, ClipboardList, Plane, CalendarClock, Flag,
  ShieldAlert, DoorOpen, FileSignature, Shield, type LucideIcon,
} from "lucide-react";

export type Feature = {
  title: string;
  description: string;
  iconName: string;
  status: "live" | "planned";
};

export type Module = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  icon: LucideIcon;
  phase: number;
  category: string;
  features: Feature[];
  highlights: string[];
  image: string;
  accentHex: string;
};

const u = (id: string) => `https://images.unsplash.com/${id}?w=1400&q=80&auto=format&fit=crop`;

export const modules: Module[] = [
  {
    slug: "people", name: "People — Core HR", tagline: "Core HR & Workforce",
    description: "The heart of the platform. Manages the complete employee lifecycle from hire to exit.",
    longDescription: "People is your single source of truth for everyone in the company. Profiles, attendance, leave, and lifecycle events — searchable, filterable, and beautifully organised.",
    icon: Users, phase: 1, category: "HR & Workforce",
    image: u("photo-1521737604893-d14cc237f11d"),
    accentHex: "#10b981",
    features: [
      { title: "Employee directory", description: "Searchable database of all employees with detailed profiles, contact info, and roles.", iconName: "Users", status: "live" },
      { title: "Department management", description: "Create and organize departments, sub-departments, and assign reporting structures.", iconName: "Network", status: "live" },
      { title: "Role-based access", description: "Granular access control allowing specific permissions for admins, managers, and employees.", iconName: "Lock", status: "live" },
      { title: "Attendance tracking", description: "Real-time clock-in and clock-out with geolocation and IP address tracking.", iconName: "Clock", status: "live" },
      { title: "Leave management", description: "Automated leave quotas, multi-level approval workflows, and balance tracking.", iconName: "CalendarDays", status: "live" },
      { title: "Holiday calendar", description: "Centralized company holiday calendar with branch-specific exceptions.", iconName: "Calendar", status: "live" },
      { title: "Exportable reports", description: "Generate Excel and PDF reports for attendance, leave, and employee data instantly.", iconName: "FileDown", status: "live" },
      { title: "Document storage", description: "Securely store contracts, IDs, and certificates with expiration alerts.", iconName: "FileText", status: "planned" },
      { title: "Onboarding checklists", description: "Automated task lists for new hires to ensure a smooth onboarding process.", iconName: "ListTodo", status: "planned" },
      { title: "Visual org chart", description: "Auto-generated, interactive organization chart showing reporting lines.", iconName: "GitMerge", status: "planned" },
      { title: "Announcements board", description: "Company-wide digital notice board with read-receipts and engagement tracking.", iconName: "Megaphone", status: "planned" },
      { title: "Shift scheduling", description: "Advanced roster scheduling, shift swaps, and coverage management.", iconName: "CalendarClock", status: "planned" },
    ],
    highlights: ["Smart directory", "Attendance tracking", "Leave policies", "Access control"],
  },
  {
    slug: "projects", name: "Projects", tagline: "Task & Project Management",
    description: "Keep every project on track with task management built directly into your HR hub.",
    longDescription: "Projects gives every team a flexible way to track work — from onboarding plans to compliance audits — with Kanban boards, comments, file attachments, and due-date nudges.",
    icon: KanbanSquare, phase: 1, category: "Productivity",
    image: u("photo-1611224923853-80b023f02d71"),
    accentHex: "#8b5cf6",
    features: [
      { title: "Project workspaces", description: "Create dedicated workspaces for teams or specific initiatives with custom access.", iconName: "FolderKanban", status: "live" },
      { title: "Task assignments", description: "Assign tasks to individuals or groups with deadlines and priority levels.", iconName: "UserCheck", status: "live" },
      { title: "Kanban boards", description: "Visual drag-and-drop boards to track tasks through various custom statuses.", iconName: "KanbanSquare", status: "live" },
      { title: "Task comments", description: "Threaded discussions directly on tasks, with @mentions and attachments.", iconName: "MessageSquare", status: "planned" },
      { title: "File attachments", description: "Upload and link files directly to tasks for centralized asset management.", iconName: "Paperclip", status: "planned" },
      { title: "Gantt view", description: "Interactive timeline view for project planning and dependency tracking.", iconName: "GanttChartSquare", status: "planned" },
      { title: "Progress tracking", description: "Automated calculation of project completion percentage based on task statuses.", iconName: "Activity", status: "planned" },
      { title: "Time tracking", description: "Log billable and non-billable hours directly against specific tasks.", iconName: "Timer", status: "planned" },
      { title: "Milestones", description: "Set major project milestones and track sprints for agile teams.", iconName: "Flag", status: "planned" },
    ],
    highlights: ["Kanban boards", "Task assignments", "Project timelines", "Time tracking"],
  },
  {
    slug: "desk", name: "Desk — Helpdesk", tagline: "Internal Ticketing",
    description: "A built-in ticketing system so employees can raise requests to the right teams instantly.",
    longDescription: "Desk turns every internal request into a tracked ticket — HR questions, IT issues, facility requests — with categories, priorities, SLAs, and a clean agent inbox.",
    icon: LifeBuoy, phase: 1, category: "Support",
    image: u("photo-1556761175-5973dc0f32e7"),
    accentHex: "#ef4444",
    features: [
      { title: "Ticket creation", description: "Simple form for employees to raise issues, complete with screenshots.", iconName: "Ticket", status: "live" },
      { title: "Smart routing", description: "Automatically assign tickets to the correct department or agent.", iconName: "Workflow", status: "live" },
      { title: "Status tracking", description: "Real-time updates on ticket status for absolute transparency.", iconName: "Activity", status: "live" },
      { title: "Priority levels", description: "Categorize issues from Low to Critical to ensure rapid response.", iconName: "AlertTriangle", status: "planned" },
      { title: "Custom categories", description: "Create specific request categories for IT, HR, Finance, and Maintenance.", iconName: "Tags", status: "planned" },
      { title: "Internal notes", description: "Private notes visible only to agents for internal collaboration.", iconName: "StickyNote", status: "planned" },
      { title: "SLA timers", description: "Enforce Service Level Agreements with auto-escalation for overdue tickets.", iconName: "Hourglass", status: "planned" },
      { title: "CSAT ratings", description: "Collect satisfaction scores automatically upon ticket resolution.", iconName: "Star", status: "planned" },
    ],
    highlights: ["Ticket tracking", "SLA timers", "Priority levels", "Agent inbox"],
  },
  {
    slug: "payroll", name: "Payroll", tagline: "Salary & Deductions",
    description: "End-to-end payroll processing — from salary configuration to downloadable payslips.",
    longDescription: "Payroll handles the entire monthly cycle — earnings, deductions, taxes, statutory contributions — and generates branded PDF salary slips for every employee automatically.",
    icon: Wallet, phase: 3, category: "Finance",
    image: u("photo-1554224155-6726b3ff858f"),
    accentHex: "#22c55e",
    features: [
      { title: "PDF Payslips", description: "Automatically generate branded, secure PDF salary slips.", iconName: "FileText", status: "planned" },
      { title: "Salary structures", description: "Configure complex gross and net salary structures with custom formulas.", iconName: "Calculator", status: "planned" },
      { title: "Auto-deductions", description: "Seamlessly link attendance and leave to calculate unpaid absences.", iconName: "MinusCircle", status: "planned" },
      { title: "Allowances", description: "Manage housing, transport, medical, and custom allowances easily.", iconName: "PlusCircle", status: "planned" },
      { title: "Payroll workflow", description: "Structured monthly processing with maker-checker approval chains.", iconName: "Workflow", status: "planned" },
      { title: "Payroll history", description: "Secure, easily accessible archive of all past payroll runs.", iconName: "History", status: "planned" },
      { title: "Tax calculations", description: "Automated calculation of income tax and statutory contributions.", iconName: "Landmark", status: "planned" },
    ],
    highlights: ["PDF payslips", "Tax calculations", "Auto-deductions", "Allowances"],
  },
  {
    slug: "recruit", name: "Recruit", tagline: "Applicant Tracking System",
    description: "A full applicant tracking system built directly inside your HR platform.",
    longDescription: "Recruit is a modern ATS built into your HR platform. Publish jobs, source candidates, run interview loops, and hire — without context-switching to a separate tool.",
    icon: UserPlus, phase: 4, category: "Talent Acquisition",
    image: u("photo-1573497019940-1c28c88b4f3e"),
    accentHex: "#14b8a6",
    features: [
      { title: "Job postings", description: "Create and publish branded job descriptions to your careers page.", iconName: "Briefcase", status: "planned" },
      { title: "Candidate pipeline", description: "Track applicants through custom stages: Applied, Interviewed, Hired.", iconName: "GitMerge", status: "planned" },
      { title: "Interview scheduling", description: "Seamless calendar integration to schedule interviews and send invites.", iconName: "Calendar", status: "planned" },
      { title: "Offer letters", description: "Generate and send automated offer letters with digital signatures.", iconName: "Mail", status: "planned" },
      { title: "One-click hire", description: "Convert successful candidates into employee profiles instantly.", iconName: "UserPlus", status: "planned" },
    ],
    highlights: ["Candidate pipelines", "Interview scheduling", "Offer letters", "Job postings"],
  },
  {
    slug: "cliq", name: "Cliq — Team Chat", tagline: "Internal Communication",
    description: "Real-time messaging woven into the platform so your team never needs to switch apps.",
    longDescription: "Cliq is Slack-style chat built into your HR workspace. Channels, DMs, threads, file sharing, and presence — without juggling another app or another login.",
    icon: MessagesSquare, phase: 4, category: "Communication",
    image: u("photo-1531545514256-b1400bc00f31"),
    accentHex: "#3b82f6",
    features: [
      { title: "Direct messaging", description: "Instant 1-on-1 chat for quick communication.", iconName: "MessageCircle", status: "planned" },
      { title: "Group channels", description: "Public and private channels organized by team, project, or topic.", iconName: "Hash", status: "planned" },
      { title: "File sharing", description: "Drag and drop documents, images, and videos directly into chats.", iconName: "Share2", status: "planned" },
      { title: "Push notifications", description: "Desktop and mobile alerts ensure you never miss a critical message.", iconName: "Bell", status: "planned" },
      { title: "Pinned messages", description: "Keep important announcements and links easily accessible.", iconName: "Pin", status: "planned" },
    ],
    highlights: ["Direct messaging", "Group channels", "File sharing", "Notifications"],
  },
  {
    slug: "analytics", name: "Analytics", tagline: "Data & Reporting",
    description: "Turn workforce data into clear, actionable dashboards and exportable reports.",
    longDescription: "Analytics turns operational data into insight. Pre-built HR dashboards, ad-hoc reports, and one-click Excel exports across every module — no BI tool required.",
    icon: BarChart3, phase: 3, category: "Reporting",
    image: u("photo-1551288049-bebda4e38f71"),
    accentHex: "#a855f7",
    features: [
      { title: "Headcount dashboard", description: "Visual breakdowns of employee distribution by department and role.", iconName: "PieChart", status: "planned" },
      { title: "Attendance trends", description: "Analyze late arrivals, early departures, and overall absenteeism.", iconName: "TrendingUp", status: "planned" },
      { title: "Leave reports", description: "Track leave utilization and liabilities across the organization.", iconName: "BarChart", status: "planned" },
      { title: "Performance charts", description: "Aggregate performance review scores to identify top talent.", iconName: "LineChart", status: "planned" },
      { title: "Custom filtering", description: "Slice and dice data with advanced date-range and attribute filters.", iconName: "Filter", status: "planned" },
      { title: "One-click exports", description: "Export any chart or table instantly to Excel, CSV, or PDF.", iconName: "Download", status: "planned" },
    ],
    highlights: ["HR Dashboards", "Exportable reports", "Trend charts", "Attendance analytics"],
  },
  {
    slug: "performance", name: "Performance", tagline: "Reviews & Appraisals",
    description: "Structure, track, and reward employee growth with a full performance management cycle.",
    longDescription: "Performance powers continuous and cyclical reviews — KPIs, 360-degree feedback, calibration, and 1:1 notes that managers and employees actually want to use.",
    icon: Target, phase: 3, category: "People Development",
    image: u("photo-1552664730-d307ca884978"),
    accentHex: "#ec4899",
    features: [
      { title: "KPI tracking", description: "Set, monitor, and evaluate Key Performance Indicators.", iconName: "Target", status: "planned" },
      { title: "360-degree reviews", description: "Gather comprehensive feedback from peers, subordinates, and managers.", iconName: "RefreshCcw", status: "planned" },
      { title: "Self-assessments", description: "Empower employees to reflect on their own achievements and challenges.", iconName: "UserCheck", status: "planned" },
      { title: "Manager appraisals", description: "Structured workflows for managers to score and finalize reviews.", iconName: "Award", status: "planned" },
      { title: "Score dashboards", description: "Historical view of an employee's performance trajectory.", iconName: "LineChart", status: "planned" },
    ],
    highlights: ["360 reviews", "Appraisals", "Goal setting", "Score dashboards"],
  },
  {
    slug: "expenses", name: "Expenses", tagline: "Claims & Reimbursements",
    description: "Track and reimburse employee spending without spreadsheets or manual processes.",
    longDescription: "Expenses kills the receipt envelope. Snap, upload, categorise — managers approve, finance reimburses, and budgets stay in check.",
    icon: Receipt, phase: 3, category: "Finance",
    image: u("photo-1554224155-8d04cb21cd6c"),
    accentHex: "#f43f5e",
    features: [
      { title: "Receipt uploads", description: "Snap photos of receipts directly via the mobile app.", iconName: "Camera", status: "planned" },
      { title: "Multi-category claims", description: "Categorize expenses into travel, food, equipment, and more.", iconName: "Tags", status: "planned" },
      { title: "Approval workflows", description: "Multi-level manager and finance team approval chains.", iconName: "CheckCircle", status: "planned" },
      { title: "Status tracking", description: "Employees can track their reimbursement status in real-time.", iconName: "Activity", status: "planned" },
      { title: "Payroll integration", description: "Approved expenses are automatically added to the next payslip.", iconName: "Link", status: "planned" },
      { title: "Spending limits", description: "Enforce company policies with hard and soft spending limits.", iconName: "Shield", status: "planned" },
    ],
    highlights: ["Receipt uploads", "Manager approvals", "Payroll integration", "Policy limits"],
  },
  {
    slug: "assets", name: "Assets", tagline: "Equipment Management",
    description: "Know exactly who has what company equipment — at all times.",
    longDescription: "Assets tracks every laptop, monitor, and access card from procurement to retirement, with depreciation schedules and clean return workflows.",
    icon: Laptop, phase: 3, category: "Operations",
    image: u("photo-1517336714731-489689fd1ca8"),
    accentHex: "#0ea5e9",
    features: [
      { title: "Asset register", description: "Central inventory for laptops, phones, vehicles, and furniture.", iconName: "Database", status: "planned" },
      { title: "Assignment records", description: "Track who holds which asset, including assignment dates.", iconName: "UserCheck", status: "planned" },
      { title: "Condition tracking", description: "Log the physical condition of assets (New, Good, Damaged, Retired).", iconName: "Activity", status: "planned" },
      { title: "Return workflows", description: "Structured process for asset handover during offboarding.", iconName: "Undo", status: "planned" },
      { title: "Maintenance reminders", description: "Automated alerts for software licenses and hardware servicing.", iconName: "Wrench", status: "planned" },
      { title: "Depreciation tracking", description: "Calculate asset value over time for accounting purposes.", iconName: "TrendingDown", status: "planned" },
    ],
    highlights: ["Asset register", "Handover records", "Depreciation", "Maintenance reminders"],
  },
  {
    slug: "training", name: "Training", tagline: "Learning & Development",
    description: "Upskill your team from inside the platform — no third-party LMS needed.",
    longDescription: "Training is your in-house LMS. Build courses with video and quizzes, track completion, issue branded certificates, and identify skill gaps across teams.",
    icon: GraduationCap, phase: 4, category: "People Development",
    image: u("photo-1522202176988-66273c2fd55f"),
    accentHex: "#84cc16",
    features: [
      { title: "Course creation", description: "Build rich courses using video, documents, and interactive quizzes.", iconName: "BookOpen", status: "planned" },
      { title: "Employee enrollment", description: "Assign specific courses to individuals or entire departments.", iconName: "Users", status: "planned" },
      { title: "Progress tracking", description: "Monitor completion rates and quiz scores in real-time.", iconName: "BarChart", status: "planned" },
      { title: "Certificates", description: "Auto-generate branded certificates upon successful completion.", iconName: "Award", status: "planned" },
      { title: "Mandatory compliance", description: "Enforce required compliance training based on roles.", iconName: "ShieldAlert", status: "planned" },
      { title: "Skill gap reports", description: "Identify areas where the team needs additional training.", iconName: "TrendingUp", status: "planned" },
    ],
    highlights: ["Course creation", "Progress tracking", "Certificates", "Skill gaps"],
  },
  {
    slug: "surveys", name: "Surveys & Feedback", tagline: "Pulse & Engagement",
    description: "Understand your workforce beyond the numbers — gather honest, structured feedback.",
    longDescription: "Surveys lets you measure engagement continuously. Pulse surveys, eNPS, and anonymous feedback channels with trend dashboards leaders actually read.",
    icon: ClipboardList, phase: 4, category: "Engagement",
    image: u("photo-1552664730-d307ca884978"),
    accentHex: "#eab308",
    features: [
      { title: "Custom surveys", description: "Create surveys with multiple choice, ratings, and open-text questions.", iconName: "FormInput", status: "planned" },
      { title: "Targeted audiences", description: "Send surveys only to specific teams, locations, or roles.", iconName: "Target", status: "planned" },
      { title: "Anonymous mode", description: "Allow employees to provide completely untraceable feedback.", iconName: "Ghost", status: "planned" },
      { title: "Pulse surveys", description: "Schedule recurring micro-surveys to track sentiment over time.", iconName: "Activity", status: "planned" },
      { title: "eNPS tracking", description: "Built-in Employee Net Promoter Score tracking and visualization.", iconName: "LineChart", status: "planned" },
    ],
    highlights: ["Custom surveys", "Anonymous feedback", "eNPS", "Real-time results"],
  },
  {
    slug: "approvals", name: "Approvals", tagline: "Workflow Management",
    description: "One unified inbox for every pending decision — across all modules.",
    longDescription: "Approvals puts every pending decision in one inbox and every contract in one template library — with native e-signature support so nothing leaves the platform.",
    icon: FileSignature, phase: 4, category: "Workflow",
    image: u("photo-1450101499163-c8848c66ca85"),
    accentHex: "#7c3aed",
    features: [
      { title: "Central inbox", description: "Review leaves, expenses, and travel requests in a single view.", iconName: "Inbox", status: "planned" },
      { title: "Multi-level chains", description: "Configure complex approval routing (e.g., Manager → HR → Finance).", iconName: "GitMerge", status: "planned" },
      { title: "Delegation", description: "Temporarily assign approval rights to a colleague while on leave.", iconName: "UserCog", status: "planned" },
      { title: "Deadline reminders", description: "Automated nudges for pending requests to prevent bottlenecks.", iconName: "BellRing", status: "planned" },
      { title: "Audit trails", description: "Immutable logs of exactly who approved what, and when.", iconName: "History", status: "planned" },
    ],
    highlights: ["Unified inbox", "Multi-level chains", "Audit trail", "Delegation"],
  },
  {
    slug: "travel", name: "Travel", tagline: "Business Trips & Policies",
    description: "Manage business travel end-to-end without a separate tool.",
    longDescription: "Travel manages business trips end-to-end — requests, itineraries, per diem calculations, and policy enforcement — synced with Expenses for clean reimbursement.",
    icon: Plane, phase: 4, category: "Operations",
    image: u("photo-1488646953014-85cb44e25828"),
    accentHex: "#0284c7",
    features: [
      { title: "Travel requests", description: "Submit trip details including destination, dates, and business purpose.", iconName: "Plane", status: "planned" },
      { title: "Manager approvals", description: "Workflow routing for travel authorization.", iconName: "CheckSquare", status: "planned" },
      { title: "Preference capture", description: "Store employee seat, meal, and hotel preferences.", iconName: "Heart", status: "planned" },
      { title: "Per diem calculation", description: "Automated daily allowance calculations based on destination.", iconName: "Calculator", status: "planned" },
      { title: "Policy enforcement", description: "Automatically flag requests that exceed class limits or budget caps.", iconName: "ShieldAlert", status: "planned" },
    ],
    highlights: ["Travel requests", "Per diem", "Expense linking", "Policy enforcement"],
  },
  {
    slug: "shifts", name: "Shifts & Scheduling", tagline: "Workforce Rosters",
    description: "Build rosters, manage shift swaps, and track coverage in real time.",
    longDescription: "Shifts is for teams that work in rotations — retail, healthcare, support. Build rosters, approve swaps, and get alerted before a shift goes uncovered.",
    icon: CalendarClock, phase: 4, category: "Operations",
    image: u("photo-1506784983877-45594efa4cbe"),
    accentHex: "#f97316",
    features: [
      { title: "Drag-and-drop builder", description: "Visually construct weekly and monthly shift rosters.", iconName: "MousePointerClick", status: "planned" },
      { title: "Shift swaps", description: "Allow employees to request shift changes with manager approval.", iconName: "Repeat", status: "planned" },
      { title: "Overtime alerts", description: "Receive warnings when an employee approaches overtime limits.", iconName: "AlertTriangle", status: "planned" },
      { title: "Coverage warnings", description: "Identify gaps in the schedule before they impact operations.", iconName: "Search", status: "planned" },
      { title: "Automated notifications", description: "Notify employees instantly via push when their schedule changes.", iconName: "Bell", status: "planned" },
    ],
    highlights: ["Shift builder", "Roster views", "Swap requests", "Coverage warnings"],
  },
  {
    slug: "contracts", name: "Contracts & Letters", tagline: "HR Document Generation",
    description: "Generate official HR documents in seconds — no Word templates needed.",
    longDescription: "Contracts & Letters handles official documentation. Generate offers, warnings, and NOCs directly from employee profiles with digital signatures.",
    icon: FileSignature, phase: 4, category: "HR & Compliance",
    image: u("photo-1450101499163-c8848c66ca85"),
    accentHex: "#475569",
    features: [
      { title: "Template library", description: "Pre-built templates for offers, promotions, warnings, and NOCs.", iconName: "Files", status: "planned" },
      { title: "Auto-fill variables", description: "Automatically populate documents with employee profile data.", iconName: "Wand2", status: "planned" },
      { title: "Digital signatures", description: "Legally binding e-signatures directly within the platform.", iconName: "PenTool", status: "planned" },
      { title: "Document tracking", description: "Monitor the status of signed versus unsigned documents.", iconName: "Eye", status: "planned" },
      { title: "Custom builder", description: "Create proprietary document templates with a rich text editor.", iconName: "Layout", status: "planned" },
    ],
    highlights: ["Template library", "Auto-fill", "Digital signatures", "Tracking"],
  },
  {
    slug: "goals", name: "Goals & OKRs", tagline: "Company Objectives",
    description: "Set, track, and align individual and team goals with company objectives.",
    longDescription: "Goals & OKRs aligns the whole company. Set company objectives, cascade to teams and individuals, run weekly check-ins, and track confidence scores.",
    icon: Flag, phase: 4, category: "People Development",
    image: u("photo-1552664730-d307ca884978"),
    accentHex: "#d946ef",
    features: [
      { title: "Goal setting", description: "Define objectives for the company, departments, or individuals.", iconName: "Target", status: "planned" },
      { title: "OKR framework", description: "Structure goals using the proven Objectives and Key Results methodology.", iconName: "ListChecks", status: "planned" },
      { title: "Progress check-ins", description: "Mandate regular updates to keep goals top of mind.", iconName: "RefreshCw", status: "planned" },
      { title: "Goal alignment", description: "Visually link individual efforts to high-level company objectives.", iconName: "GitMerge", status: "planned" },
      { title: "Completion reports", description: "Analyze goal success rates across the organization.", iconName: "BarChart", status: "planned" },
    ],
    highlights: ["OKR framework", "Goal alignment", "Progress check-ins", "Reporting"],
  },
  {
    slug: "compliance", name: "Disciplinary & Compliance", tagline: "Incident Tracking",
    description: "Handle sensitive HR cases properly, confidentially, and with a full paper trail.",
    longDescription: "Compliance handles the sensitive end of HR — warnings, disciplinary cases, incident reports — with restricted access, audit trails, and document-grade record-keeping.",
    icon: ShieldAlert, phase: 4, category: "HR & Compliance",
    image: u("photo-1521791136064-7986c2920216"),
    accentHex: "#dc2626",
    features: [
      { title: "Incident reporting", description: "Secure, confidential portal for employees to report misconduct.", iconName: "AlertOctagon", status: "planned" },
      { title: "Formal warnings", description: "Issue and track verbal, written, and final warnings.", iconName: "FileWarning", status: "planned" },
      { title: "Case tracking", description: "Monitor the timeline and status of active disciplinary investigations.", iconName: "Activity", status: "planned" },
      { title: "Restricted access", description: "Highly sensitive files visible only to authorized personnel.", iconName: "Lock", status: "planned" },
      { title: "Resolution recording", description: "Log the outcomes and disciplinary actions taken.", iconName: "CheckCircle", status: "planned" },
    ],
    highlights: ["Incident reporting", "Formal warnings", "Confidential files", "Timeline tracking"],
  },
  {
    slug: "exit", name: "Exit Management", tagline: "Structured Offboarding",
    description: "Make offboarding as structured and professional as onboarding.",
    longDescription: "Exit Management turns goodbyes into graceful transitions. Resignation flows, offboarding checklists, structured exit interviews, and an alumni directory you can re-engage later.",
    icon: DoorOpen, phase: 4, category: "HR & Workforce",
    image: u("photo-1521737711867-e3b97375f902"),
    accentHex: "#64748b",
    features: [
      { title: "Resignation workflow", description: "Digital submission and managerial approval of resignations.", iconName: "LogOut", status: "planned" },
      { title: "Exit checklists", description: "Task lists for asset return, handover, and access revocation.", iconName: "ListTodo", status: "planned" },
      { title: "Exit interviews", description: "Structured forms to gather feedback on why employees leave.", iconName: "MessageSquare", status: "planned" },
      { title: "Settlement calculation", description: "Automated final pay, gratuity, and leave encashment calculations.", iconName: "Calculator", status: "planned" },
      { title: "Alumni directory", description: "Maintain records of past employees and rehire eligibility.", iconName: "Users", status: "planned" },
    ],
    highlights: ["Exit checklists", "Settlement calculation", "Clearance approvals", "Alumni records"],
  },
  {
    slug: "admin", name: "Admin Panel", tagline: "Command Centre",
    description: "The control centre for super admins — manage the entire platform, users, and configuration from one place.",
    longDescription: "The Admin Panel is mission control for ByThawkHR. Configure your organisation, invite users, assign roles, toggle modules per plan or department, and review a full audit trail of every change made across the platform.",
    icon: Shield, phase: 1, category: "Core — Always On",
    image: u("photo-1551288049-bebda4e38f71"),
    accentHex: "#6366f1",
    features: [
      { title: "Company profile", description: "Set up core details: logo, timezone, currency, and fiscal year.", iconName: "Building", status: "live" },
      { title: "Multi-branch support", description: "Manage multiple geographic locations under one organization.", iconName: "MapPin", status: "live" },
      { title: "Granular permissions", description: "Create custom roles with exact read/write permissions per module.", iconName: "ShieldCheck", status: "live" },
      { title: "Module toggles", description: "Enable or disable specific modules for the entire org or specific roles.", iconName: "ToggleRight", status: "live" },
      { title: "Audit logs", description: "Immutable record of every action taken in the platform, by whom.", iconName: "History", status: "live" },
      { title: "Security controls", description: "Enforce 2FA, IP whitelisting, and strict password policies.", iconName: "Lock", status: "live" },
      { title: "Bulk import", description: "Easily migrate data using Excel or CSV templates.", iconName: "UploadCloud", status: "live" },
      { title: "Data export", description: "Generate full backups of your organizational data on demand.", iconName: "DownloadCloud", status: "live" },
    ],
    highlights: ["Global configuration", "Audit logging", "Access control", "Module toggles"],
  },
];

export const getModule = (slug: string) => modules.find((m) => m.slug === slug);
