import {
  Users, Clock, CalendarDays, KanbanSquare, LifeBuoy, Wallet,
  Receipt, Laptop, BarChart3, Target, UserPlus, MessagesSquare,
  GraduationCap, ClipboardList, Plane, CalendarClock, Flag,
  ShieldAlert, DoorOpen, FileSignature, Shield, type LucideIcon,
} from "lucide-react";

export type Module = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  icon: LucideIcon;
  phase: 1 | 2 | 3 | 4;
  category: "Core HR" | "Operations" | "Finance" | "Talent" | "Engagement" | "Governance";
  features: { title: string; body: string }[];
  highlights: string[];
  image: string;
  accentHex: string;
};

const u = (id: string) => `https://images.unsplash.com/${id}?w=1400&q=80&auto=format&fit=crop`;

export const modules: Module[] = [
  {
    slug: "admin", name: "Admin Panel", tagline: "Platform, users & module control",
    description: "Provision tenants, manage roles, toggle modules per plan, and audit every action from one console.",
    longDescription: "The Admin Panel is mission control for ByThawkHR. Configure your organisation, invite users, assign roles, toggle modules per plan or department, and review a full audit trail of every change made across the platform.",
    icon: Shield, phase: 1, category: "Governance",
    image: u("photo-1551288049-bebda4e38f71"),
    accentHex: "#6366f1",
    features: [
      { title: "Tenant provisioning", body: "Create and isolate organisations with strict orgId scoping baked in." },
      { title: "Role-based access", body: "Compose granular permissions per role, department, or individual." },
      { title: "Module toggles", body: "Turn modules on/off per subscription plan, instantly reflected in every client." },
      { title: "Audit log", body: "Immutable, exportable log of every user and system action." },
    ],
    highlights: ["SSO ready", "SCIM provisioning", "Audit exports", "Plan controls"],
  },
  {
    slug: "people", name: "People", tagline: "Core HR directory & profiles",
    description: "A living employee directory with org structure, roles, documents, and lifecycle history.",
    longDescription: "People is your single source of truth for everyone in the company. Profiles, contracts, documents, reporting lines, and lifecycle events — searchable, filterable, and beautifully organised.",
    icon: Users, phase: 1, category: "Core HR",
    image: u("photo-1521737604893-d14cc237f11d"),
    accentHex: "#10b981",
    features: [
      { title: "Smart directory", body: "Search by name, team, skill, location, or any custom field you define." },
      { title: "Org chart", body: "Auto-generated visual hierarchy with drag-to-reorganise." },
      { title: "Document vault", body: "Per-employee documents with expiry alerts and signature status." },
      { title: "Lifecycle timeline", body: "Every promotion, transfer, and milestone recorded in one place." },
    ],
    highlights: ["Custom fields", "Org chart", "Document expiry", "Lifecycle history"],
  },
  {
    slug: "attendance", name: "Attendance", tagline: "Clock-in, geofencing & overtime",
    description: "Web & mobile clock-in with geolocation, shift detection, overtime calculation, and offline queue.",
    longDescription: "Attendance handles every way work happens — office, remote, field, or hybrid. Geofenced clock-ins, biometric pairing, automatic overtime, and an offline-first mobile app that never loses a punch.",
    icon: Clock, phase: 1, category: "Core HR",
    image: u("photo-1611224923853-80b023f02d71"),
    accentHex: "#f59e0b",
    features: [
      { title: "Geofenced clock-in", body: "Restrict punches to office radii, client sites, or custom zones." },
      { title: "Offline sync", body: "Mobile app queues punches with Hive and replays the moment you reconnect." },
      { title: "Overtime engine", body: "Configurable OT rules with policy-driven multipliers and caps." },
      { title: "Timesheet view", body: "Daily, weekly, and monthly views with anomaly highlighting." },
    ],
    highlights: ["Geofence", "Offline-first", "OT rules", "Biometric"],
  },
  {
    slug: "leave", name: "Leave", tagline: "Balances, requests & approvals",
    description: "Policy-driven balances, request flows, manager approvals, and team calendar visibility.",
    longDescription: "Leave makes time-off effortless. Configure policies, accruals, and carry-forwards once; employees apply in seconds; managers approve from email, web, or mobile.",
    icon: CalendarDays, phase: 1, category: "Core HR",
    image: u("photo-1506784983877-45594efa4cbe"),
    accentHex: "#06b6d4",
    features: [
      { title: "Policy engine", body: "Country, role, or tenure-based accruals with carry-forward and encashment." },
      { title: "Team calendar", body: "See who's off this week without the spreadsheet ritual." },
      { title: "Approval chains", body: "Single or multi-level approvals routed through manager hierarchy." },
      { title: "Holiday lists", body: "Per-location holiday calendars with smart suggestions." },
    ],
    highlights: ["Accruals", "Multi-approver", "Team calendar", "Carry-forward"],
  },
  {
    slug: "projects", name: "Projects", tagline: "Tasks, Kanban & collaboration",
    description: "Lightweight projects with Kanban, assignees, comments, and file attachments — built for HR ops and beyond.",
    longDescription: "Projects gives every team a flexible way to track work — from onboarding plans to compliance audits — with Kanban boards, comments, file attachments, and due-date nudges.",
    icon: KanbanSquare, phase: 1, category: "Operations",
    image: u("photo-1611224923853-80b023f02d71"),
    accentHex: "#8b5cf6",
    features: [
      { title: "Drag-and-drop Kanban", body: "Built with dnd-kit for buttery-smooth board interactions." },
      { title: "Comments & mentions", body: "Discuss tasks inline, with @mentions that notify in real time." },
      { title: "Attachments", body: "Files via Cloudinary with previews and version history." },
      { title: "Due-date nudges", body: "Smart reminders before things slip." },
    ],
    highlights: ["Kanban", "Mentions", "Attachments", "Reminders"],
  },
  {
    slug: "desk", name: "Desk", tagline: "Internal helpdesk & tickets",
    description: "Ticketing for HR, IT, and Admin with priorities, categories, SLAs, and SLA breach alerts.",
    longDescription: "Desk turns every internal request into a tracked ticket — HR questions, IT issues, facility requests — with categories, priorities, SLAs, and a clean agent inbox.",
    icon: LifeBuoy, phase: 1, category: "Operations",
    image: u("photo-1556761175-5973dc0f32e7"),
    accentHex: "#ef4444",
    features: [
      { title: "Multi-queue inbox", body: "Separate queues for HR, IT, Admin — or any team you need." },
      { title: "SLA timers", body: "First response and resolution timers with breach alerts." },
      { title: "Canned replies", body: "Save common responses and reuse them in one click." },
      { title: "Customer view", body: "Employees see their own tickets and statuses, end-to-end." },
    ],
    highlights: ["SLAs", "Queues", "Canned replies", "Categories"],
  },
  {
    slug: "payroll", name: "Payroll", tagline: "Slips, deductions & tax",
    description: "Run payroll with components, deductions, tax rules, and downloadable salary slips per cycle.",
    longDescription: "Payroll handles the entire monthly cycle — earnings, deductions, taxes, statutory contributions — and generates branded PDF salary slips for every employee automatically.",
    icon: Wallet, phase: 3, category: "Finance",
    image: u("photo-1554224155-6726b3ff858f"),
    accentHex: "#22c55e",
    features: [
      { title: "Component builder", body: "Define earnings and deductions with formulas and per-employee overrides." },
      { title: "Tax engine", body: "Slab-based tax computation with statutory contributions." },
      { title: "PDF salary slips", body: "Branded slips generated via PDFKit/Puppeteer in a background queue." },
      { title: "Payroll history", body: "Full archive of every cycle, searchable and exportable." },
    ],
    highlights: ["Tax slabs", "PDF slips", "Statutory", "History"],
  },
  {
    slug: "expenses", name: "Expenses", tagline: "Claims, receipts & reimbursement",
    description: "Snap receipts, file claims, and route them through approval chains tied to budgets.",
    longDescription: "Expenses kills the receipt envelope. Snap, upload, categorise — managers approve, finance reimburses, and budgets stay in check.",
    icon: Receipt, phase: 3, category: "Finance",
    image: u("photo-1554224155-8d04cb21cd6c"),
    accentHex: "#f43f5e",
    features: [
      { title: "Receipt capture", body: "Mobile-first receipt scanning with auto-categorisation." },
      { title: "Approval chains", body: "Multi-level approvals tied to amount thresholds." },
      { title: "Budget tracking", body: "Per-team and per-category budgets with live burn-down." },
      { title: "Multi-currency", body: "FX-aware claims with auto-conversion to base currency." },
    ],
    highlights: ["OCR receipts", "Multi-currency", "Budgets", "Mileage"],
  },
  {
    slug: "assets", name: "Assets", tagline: "Equipment & lifecycle",
    description: "Assign laptops, devices, and accessories with depreciation tracking and return workflows.",
    longDescription: "Assets tracks every laptop, monitor, and access card from procurement to retirement, with depreciation schedules and clean return workflows.",
    icon: Laptop, phase: 3, category: "Operations",
    image: u("photo-1517336714731-489689fd1ca8"),
    accentHex: "#0ea5e9",
    features: [
      { title: "Asset register", body: "Centralised inventory with serials, vendors, and warranties." },
      { title: "Assign & return", body: "Digital handover with e-signed acknowledgements." },
      { title: "Depreciation", body: "Straight-line and WDV depreciation with monthly schedules." },
      { title: "QR labels", body: "Print QR labels that resolve to the asset's record." },
    ],
    highlights: ["Depreciation", "QR labels", "E-sign", "Warranty"],
  },
  {
    slug: "analytics", name: "Analytics", tagline: "Dashboards & exportable reports",
    description: "Real-time HR dashboards, drill-down reports, and CSV/Excel exports for any module.",
    longDescription: "Analytics turns operational data into insight. Pre-built HR dashboards, ad-hoc reports, and one-click Excel exports across every module — no BI tool required.",
    icon: BarChart3, phase: 3, category: "Governance",
    image: u("photo-1551288049-bebda4e38f71"),
    accentHex: "#a855f7",
    features: [
      { title: "Live dashboards", body: "Headcount, attrition, attendance, and DEI metrics at a glance." },
      { title: "Drill-down", body: "Click any number to see the underlying records." },
      { title: "Scheduled reports", body: "Email PDFs and Excel files on a cadence." },
      { title: "Custom reports", body: "Build your own using a visual query builder." },
    ],
    highlights: ["Live data", "Excel export", "Scheduled", "DEI"],
  },
  {
    slug: "performance", name: "Performance", tagline: "Appraisals, 360 & KPIs",
    description: "Configurable review cycles, 360-degree feedback, KPIs, and growth conversations.",
    longDescription: "Performance powers continuous and cyclical reviews — KPIs, 360-degree feedback, calibration, and 1:1 notes that managers and employees actually want to use.",
    icon: Target, phase: 3, category: "Talent",
    image: u("photo-1552664730-d307ca884978"),
    accentHex: "#ec4899",
    features: [
      { title: "Review cycles", body: "Quarterly, annual, or custom cycles with templated forms." },
      { title: "360 feedback", body: "Peer, upward, and self reviews with anonymisation options." },
      { title: "KPIs", body: "Track measurable outcomes with progress bars and check-ins." },
      { title: "1:1 notes", body: "Shared agendas and notes between manager and report." },
    ],
    highlights: ["360 reviews", "Calibration", "KPIs", "1:1s"],
  },
  {
    slug: "recruit", name: "Recruit", tagline: "ATS, jobs & interviews",
    description: "Post jobs, track candidates through pipelines, schedule interviews, and collect scorecards.",
    longDescription: "Recruit is a modern ATS built into your HR platform. Publish jobs, source candidates, run interview loops, and hire — without context-switching to a separate tool.",
    icon: UserPlus, phase: 4, category: "Talent",
    image: u("photo-1573497019940-1c28c88b4f3e"),
    accentHex: "#14b8a6",
    features: [
      { title: "Career site", body: "Branded job board generated automatically from your openings." },
      { title: "Pipeline", body: "Kanban candidate stages with bulk actions and notes." },
      { title: "Scheduling", body: "Calendar-aware interview scheduling with panel coordination." },
      { title: "Scorecards", body: "Structured interview feedback with weighted competencies." },
    ],
    highlights: ["Career site", "Pipelines", "Scorecards", "Scheduling"],
  },
  {
    slug: "cliq", name: "Cliq", tagline: "Team chat & file sharing",
    description: "Real-time chat with channels, DMs, file sharing, and presence — fully inside your workspace.",
    longDescription: "Cliq is Slack-style chat built into your HR workspace. Channels, DMs, threads, file sharing, and presence — without juggling another app or another login.",
    icon: MessagesSquare, phase: 4, category: "Engagement",
    image: u("photo-1531545514256-b1400bc00f31"),
    accentHex: "#3b82f6",
    features: [
      { title: "Channels & DMs", body: "Public, private, and direct conversations with rich text." },
      { title: "Threads", body: "Keep conversations tidy with first-class thread support." },
      { title: "File sharing", body: "Drag-and-drop files with previews and search." },
      { title: "Presence", body: "Live online/away/busy status tied to attendance." },
    ],
    highlights: ["Channels", "Threads", "Presence", "Search"],
  },
  {
    slug: "training", name: "Training", tagline: "Courses, certificates & skills",
    description: "Build courses, track completion, issue certificates, and surface skill gaps automatically.",
    longDescription: "Training is your in-house LMS. Build courses with video and quizzes, track completion, issue branded certificates, and identify skill gaps across teams.",
    icon: GraduationCap, phase: 4, category: "Talent",
    image: u("photo-1522202176988-66273c2fd55f"),
    accentHex: "#84cc16",
    features: [
      { title: "Course builder", body: "Modules, video, quizzes, and SCORM imports." },
      { title: "Certificates", body: "Auto-issued, signed, downloadable certificates on completion." },
      { title: "Skill matrix", body: "Map skills to roles and surface gaps automatically." },
      { title: "Learning paths", body: "Curate sequences for onboarding, compliance, or growth." },
    ],
    highlights: ["SCORM", "Certificates", "Skill matrix", "Paths"],
  },
  {
    slug: "surveys", name: "Surveys & Feedback", tagline: "eNPS & pulse surveys",
    description: "Run pulse surveys, anonymous feedback, and eNPS programs with trend dashboards.",
    longDescription: "Surveys lets you measure engagement continuously. Pulse surveys, eNPS, and anonymous feedback channels with trend dashboards leaders actually read.",
    icon: ClipboardList, phase: 4, category: "Engagement",
    image: u("photo-1552664730-d307ca884978"),
    accentHex: "#eab308",
    features: [
      { title: "Pulse surveys", body: "Short, scheduled surveys delivered in-app and via email." },
      { title: "eNPS", body: "Industry-standard scoring with auto-generated reports." },
      { title: "Anonymous feedback", body: "Always-on channel for raising concerns safely." },
      { title: "Trend analysis", body: "Track sentiment over time, sliced by team or location." },
    ],
    highlights: ["eNPS", "Pulses", "Anonymous", "Trends"],
  },
  {
    slug: "travel", name: "Travel", tagline: "Trips, per diem & policy",
    description: "Request trips, attach itineraries, calculate per diem, and enforce travel policy automatically.",
    longDescription: "Travel manages business trips end-to-end — requests, itineraries, per diem calculations, and policy enforcement — synced with Expenses for clean reimbursement.",
    icon: Plane, phase: 4, category: "Operations",
    image: u("photo-1488646953014-85cb44e25828"),
    accentHex: "#0284c7",
    features: [
      { title: "Trip requests", body: "Submit destinations, dates, and purpose for approval." },
      { title: "Itinerary uploads", body: "Attach tickets and bookings to keep everything together." },
      { title: "Per diem engine", body: "Auto-calculated based on city and trip duration." },
      { title: "Policy enforcement", body: "Block out-of-policy bookings before they happen." },
    ],
    highlights: ["Per diem", "Policy", "Itinerary", "Approvals"],
  },
  {
    slug: "shifts", name: "Shifts & Scheduling", tagline: "Rosters & swaps",
    description: "Build rosters, manage swap requests, and get coverage alerts before shifts go uncovered.",
    longDescription: "Shifts is for teams that work in rotations — retail, healthcare, support. Build rosters, approve swaps, and get alerted before a shift goes uncovered.",
    icon: CalendarClock, phase: 4, category: "Operations",
    image: u("photo-1506784983877-45594efa4cbe"),
    accentHex: "#f97316",
    features: [
      { title: "Roster builder", body: "Drag-and-drop weekly and monthly rosters." },
      { title: "Swap requests", body: "Employees propose swaps; managers approve in one tap." },
      { title: "Coverage alerts", body: "Real-time alerts when a shift risks being uncovered." },
      { title: "Templates", body: "Save rotation patterns and reuse them in seconds." },
    ],
    highlights: ["Rosters", "Swaps", "Coverage", "Templates"],
  },
  {
    slug: "goals", name: "Goals & OKRs", tagline: "Aligned objectives",
    description: "Cascade company OKRs to teams and individuals with check-ins and confidence scoring.",
    longDescription: "Goals & OKRs aligns the whole company. Set company objectives, cascade to teams and individuals, run weekly check-ins, and track confidence scores.",
    icon: Flag, phase: 4, category: "Talent",
    image: u("photo-1552664730-d307ca884978"),
    accentHex: "#d946ef",
    features: [
      { title: "OKR hierarchy", body: "Company → team → individual with clear alignment lines." },
      { title: "Weekly check-ins", body: "Lightweight updates with progress and blockers." },
      { title: "Confidence scoring", body: "5-point scoring that reflects realistic confidence." },
      { title: "Public dashboards", body: "Transparency by default — everyone sees the same picture." },
    ],
    highlights: ["Cascading", "Check-ins", "Confidence", "Public"],
  },
  {
    slug: "compliance", name: "Disciplinary & Compliance", tagline: "Cases & incidents",
    description: "Track warnings, disciplinary cases, and incident reports with full audit trails.",
    longDescription: "Compliance handles the sensitive end of HR — warnings, disciplinary cases, incident reports — with restricted access, audit trails, and document-grade record-keeping.",
    icon: ShieldAlert, phase: 4, category: "Governance",
    image: u("photo-1521791136064-7986c2920216"),
    accentHex: "#dc2626",
    features: [
      { title: "Restricted access", body: "Only authorised roles see case details, full audit trail." },
      { title: "Case workflow", body: "Open → investigate → resolve, with templated stages." },
      { title: "Incident reports", body: "Structured intake forms with attachments and witnesses." },
      { title: "Document vault", body: "Encrypted storage for sensitive case documents." },
    ],
    highlights: ["Restricted", "Audit trail", "Encrypted", "Workflows"],
  },
  {
    slug: "exit", name: "Exit Management", tagline: "Offboarding & alumni",
    description: "Manage resignations, offboarding checklists, exit interviews, and an alumni network.",
    longDescription: "Exit Management turns goodbyes into graceful transitions. Resignation flows, offboarding checklists, structured exit interviews, and an alumni directory you can re-engage later.",
    icon: DoorOpen, phase: 4, category: "Core HR",
    image: u("photo-1521737711867-e3b97375f902"),
    accentHex: "#64748b",
    features: [
      { title: "Resignation flow", body: "Digital notice with auto-calculated last working day." },
      { title: "Offboarding checklist", body: "Asset return, knowledge transfer, access revocation — tracked." },
      { title: "Exit interviews", body: "Structured forms with aggregate insights for leadership." },
      { title: "Alumni network", body: "Stay connected with former employees for boomerang hires." },
    ],
    highlights: ["Checklists", "Exit interviews", "Alumni", "Handover"],
  },
  {
    slug: "approvals", name: "Approvals & Contracts", tagline: "Unified inbox & e-sign",
    description: "One inbox for every approval, plus reusable contract templates with digital signatures.",
    longDescription: "Approvals & Contracts puts every pending decision in one inbox and every contract in one template library — with native e-signature support so nothing leaves the platform.",
    icon: FileSignature, phase: 4, category: "Governance",
    image: u("photo-1450101499163-c8848c66ca85"),
    accentHex: "#7c3aed",
    features: [
      { title: "Unified approval inbox", body: "Leave, expense, travel, and custom approvals in one queue." },
      { title: "Contract templates", body: "Reusable templates with mail-merge fields." },
      { title: "E-signature", body: "Native digital signing — no third-party tool needed." },
      { title: "Versioned audit", body: "Every change to every contract, signed and timestamped." },
    ],
    highlights: ["E-sign", "Templates", "Unified inbox", "Audit"],
  },
];

export const getModule = (slug: string) => modules.find((m) => m.slug === slug);
