/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as ModuleDetailRouteImport } from './routes/module-detail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as ModulesProjectsDashboardRouteImport } from './routes/modules.projects.dashboard'
import { Route as ModulesPeopleDashboardRouteImport } from './routes/modules.people.dashboard'
import { Route as ModulesPayrollDashboardRouteImport } from './routes/modules.payroll.dashboard'
import { Route as ModulesDeskDashboardRouteImport } from './routes/modules.desk.dashboard'
import { Route as ModulesSlugLoginRouteImport } from './routes/modules.$slug_.login'
import { Route as ModulesPeopleDashboardIndexRouteImport } from './routes/modules.people.dashboard.index'
import { Route as ModulesPeopleDashboardLeaveRouteImport } from './routes/modules.people.dashboard.leave'
import { Route as ModulesPeopleDashboardDirectoryRouteImport } from './routes/modules.people.dashboard.directory'
import { Route as ModulesPeopleDashboardAttendanceRouteImport } from './routes/modules.people.dashboard.attendance'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleDetailRoute = ModuleDetailRouteImport.update({
  id: '/module-detail',
  path: '/module-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesProjectsDashboardRoute =
  ModulesProjectsDashboardRouteImport.update({
    id: '/projects/dashboard',
    path: '/projects/dashboard',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesPeopleDashboardRoute = ModulesPeopleDashboardRouteImport.update({
  id: '/people/dashboard',
  path: '/people/dashboard',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesPayrollDashboardRoute = ModulesPayrollDashboardRouteImport.update({
  id: '/payroll/dashboard',
  path: '/payroll/dashboard',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesDeskDashboardRoute = ModulesDeskDashboardRouteImport.update({
  id: '/desk/dashboard',
  path: '/desk/dashboard',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSlugLoginRoute = ModulesSlugLoginRouteImport.update({
  id: '/$slug_/login',
  path: '/$slug/login',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesPeopleDashboardIndexRoute =
  ModulesPeopleDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ModulesPeopleDashboardRoute,
  } as any)
const ModulesPeopleDashboardLeaveRoute =
  ModulesPeopleDashboardLeaveRouteImport.update({
    id: '/leave',
    path: '/leave',
    getParentRoute: () => ModulesPeopleDashboardRoute,
  } as any)
const ModulesPeopleDashboardDirectoryRoute =
  ModulesPeopleDashboardDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => ModulesPeopleDashboardRoute,
  } as any)
const ModulesPeopleDashboardAttendanceRoute =
  ModulesPeopleDashboardAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ModulesPeopleDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/module-detail': typeof ModuleDetailRoute
  '/modules': typeof ModulesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/': typeof ModulesIndexRoute
  '/modules/$slug/login': typeof ModulesSlugLoginRoute
  '/modules/desk/dashboard': typeof ModulesDeskDashboardRoute
  '/modules/payroll/dashboard': typeof ModulesPayrollDashboardRoute
  '/modules/people/dashboard': typeof ModulesPeopleDashboardRouteWithChildren
  '/modules/projects/dashboard': typeof ModulesProjectsDashboardRoute
  '/modules/people/dashboard/attendance': typeof ModulesPeopleDashboardAttendanceRoute
  '/modules/people/dashboard/directory': typeof ModulesPeopleDashboardDirectoryRoute
  '/modules/people/dashboard/leave': typeof ModulesPeopleDashboardLeaveRoute
  '/modules/people/dashboard/': typeof ModulesPeopleDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/module-detail': typeof ModuleDetailRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules': typeof ModulesIndexRoute
  '/modules/$slug/login': typeof ModulesSlugLoginRoute
  '/modules/desk/dashboard': typeof ModulesDeskDashboardRoute
  '/modules/payroll/dashboard': typeof ModulesPayrollDashboardRoute
  '/modules/projects/dashboard': typeof ModulesProjectsDashboardRoute
  '/modules/people/dashboard/attendance': typeof ModulesPeopleDashboardAttendanceRoute
  '/modules/people/dashboard/directory': typeof ModulesPeopleDashboardDirectoryRoute
  '/modules/people/dashboard/leave': typeof ModulesPeopleDashboardLeaveRoute
  '/modules/people/dashboard': typeof ModulesPeopleDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/module-detail': typeof ModuleDetailRoute
  '/modules': typeof ModulesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/': typeof ModulesIndexRoute
  '/modules/$slug_/login': typeof ModulesSlugLoginRoute
  '/modules/desk/dashboard': typeof ModulesDeskDashboardRoute
  '/modules/payroll/dashboard': typeof ModulesPayrollDashboardRoute
  '/modules/people/dashboard': typeof ModulesPeopleDashboardRouteWithChildren
  '/modules/projects/dashboard': typeof ModulesProjectsDashboardRoute
  '/modules/people/dashboard/attendance': typeof ModulesPeopleDashboardAttendanceRoute
  '/modules/people/dashboard/directory': typeof ModulesPeopleDashboardDirectoryRoute
  '/modules/people/dashboard/leave': typeof ModulesPeopleDashboardLeaveRoute
  '/modules/people/dashboard/': typeof ModulesPeopleDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/integrations'
    | '/login'
    | '/module-detail'
    | '/modules'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/modules/$slug'
    | '/modules/'
    | '/modules/$slug/login'
    | '/modules/desk/dashboard'
    | '/modules/payroll/dashboard'
    | '/modules/people/dashboard'
    | '/modules/projects/dashboard'
    | '/modules/people/dashboard/attendance'
    | '/modules/people/dashboard/directory'
    | '/modules/people/dashboard/leave'
    | '/modules/people/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/integrations'
    | '/login'
    | '/module-detail'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/modules/$slug'
    | '/modules'
    | '/modules/$slug/login'
    | '/modules/desk/dashboard'
    | '/modules/payroll/dashboard'
    | '/modules/projects/dashboard'
    | '/modules/people/dashboard/attendance'
    | '/modules/people/dashboard/directory'
    | '/modules/people/dashboard/leave'
    | '/modules/people/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/integrations'
    | '/login'
    | '/module-detail'
    | '/modules'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/modules/$slug'
    | '/modules/'
    | '/modules/$slug_/login'
    | '/modules/desk/dashboard'
    | '/modules/payroll/dashboard'
    | '/modules/people/dashboard'
    | '/modules/projects/dashboard'
    | '/modules/people/dashboard/attendance'
    | '/modules/people/dashboard/directory'
    | '/modules/people/dashboard/leave'
    | '/modules/people/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  ModuleDetailRoute: typeof ModuleDetailRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module-detail': {
      id: '/module-detail'
      path: '/module-detail'
      fullPath: '/module-detail'
      preLoaderRoute: typeof ModuleDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/projects/dashboard': {
      id: '/modules/projects/dashboard'
      path: '/projects/dashboard'
      fullPath: '/modules/projects/dashboard'
      preLoaderRoute: typeof ModulesProjectsDashboardRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/people/dashboard': {
      id: '/modules/people/dashboard'
      path: '/people/dashboard'
      fullPath: '/modules/people/dashboard'
      preLoaderRoute: typeof ModulesPeopleDashboardRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/payroll/dashboard': {
      id: '/modules/payroll/dashboard'
      path: '/payroll/dashboard'
      fullPath: '/modules/payroll/dashboard'
      preLoaderRoute: typeof ModulesPayrollDashboardRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/desk/dashboard': {
      id: '/modules/desk/dashboard'
      path: '/desk/dashboard'
      fullPath: '/modules/desk/dashboard'
      preLoaderRoute: typeof ModulesDeskDashboardRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$slug_/login': {
      id: '/modules/$slug_/login'
      path: '/$slug/login'
      fullPath: '/modules/$slug/login'
      preLoaderRoute: typeof ModulesSlugLoginRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/people/dashboard/': {
      id: '/modules/people/dashboard/'
      path: '/'
      fullPath: '/modules/people/dashboard/'
      preLoaderRoute: typeof ModulesPeopleDashboardIndexRouteImport
      parentRoute: typeof ModulesPeopleDashboardRoute
    }
    '/modules/people/dashboard/leave': {
      id: '/modules/people/dashboard/leave'
      path: '/leave'
      fullPath: '/modules/people/dashboard/leave'
      preLoaderRoute: typeof ModulesPeopleDashboardLeaveRouteImport
      parentRoute: typeof ModulesPeopleDashboardRoute
    }
    '/modules/people/dashboard/directory': {
      id: '/modules/people/dashboard/directory'
      path: '/directory'
      fullPath: '/modules/people/dashboard/directory'
      preLoaderRoute: typeof ModulesPeopleDashboardDirectoryRouteImport
      parentRoute: typeof ModulesPeopleDashboardRoute
    }
    '/modules/people/dashboard/attendance': {
      id: '/modules/people/dashboard/attendance'
      path: '/attendance'
      fullPath: '/modules/people/dashboard/attendance'
      preLoaderRoute: typeof ModulesPeopleDashboardAttendanceRouteImport
      parentRoute: typeof ModulesPeopleDashboardRoute
    }
  }
}

interface ModulesPeopleDashboardRouteChildren {
  ModulesPeopleDashboardAttendanceRoute: typeof ModulesPeopleDashboardAttendanceRoute
  ModulesPeopleDashboardDirectoryRoute: typeof ModulesPeopleDashboardDirectoryRoute
  ModulesPeopleDashboardLeaveRoute: typeof ModulesPeopleDashboardLeaveRoute
  ModulesPeopleDashboardIndexRoute: typeof ModulesPeopleDashboardIndexRoute
}

const ModulesPeopleDashboardRouteChildren: ModulesPeopleDashboardRouteChildren =
  {
    ModulesPeopleDashboardAttendanceRoute:
      ModulesPeopleDashboardAttendanceRoute,
    ModulesPeopleDashboardDirectoryRoute: ModulesPeopleDashboardDirectoryRoute,
    ModulesPeopleDashboardLeaveRoute: ModulesPeopleDashboardLeaveRoute,
    ModulesPeopleDashboardIndexRoute: ModulesPeopleDashboardIndexRoute,
  }

const ModulesPeopleDashboardRouteWithChildren =
  ModulesPeopleDashboardRoute._addFileChildren(
    ModulesPeopleDashboardRouteChildren,
  )

interface ModulesRouteChildren {
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  ModulesSlugLoginRoute: typeof ModulesSlugLoginRoute
  ModulesDeskDashboardRoute: typeof ModulesDeskDashboardRoute
  ModulesPayrollDashboardRoute: typeof ModulesPayrollDashboardRoute
  ModulesPeopleDashboardRoute: typeof ModulesPeopleDashboardRouteWithChildren
  ModulesProjectsDashboardRoute: typeof ModulesProjectsDashboardRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  ModulesSlugLoginRoute: ModulesSlugLoginRoute,
  ModulesDeskDashboardRoute: ModulesDeskDashboardRoute,
  ModulesPayrollDashboardRoute: ModulesPayrollDashboardRoute,
  ModulesPeopleDashboardRoute: ModulesPeopleDashboardRouteWithChildren,
  ModulesProjectsDashboardRoute: ModulesProjectsDashboardRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  ModuleDetailRoute: ModuleDetailRoute,
  ModulesRoute: ModulesRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
